version: "3.9"

services:
  redis1:
    image: redis:7
    container_name: redis1
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - urlnet

  redis2:
    image: redis:7
    container_name: redis2
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - urlnet

  redis3:
    image: redis:7
    container_name: redis3
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - urlnet

  url-shortener:
    build: .
    container_name: url-shortener
    ports:
      - "3000:3000"
    depends_on:
      - redis1
      - redis2
      - redis3
    environment:
      PORT: 3000
      REDIS_HOST1: redis1
      REDIS_PORT1: 6379
      REDIS_HOST2: redis2
      REDIS_PORT2: 6379
      REDIS_HOST3: redis3
      REDIS_PORT3: 6379
    networks:
      - urlnet

networks:
  urlnet:
    driver: bridge
